name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically

      - name: Install bundle and jeckyll
        run: gem install jekyll bundler
  
      - name: Install dependencies
        run: bundle install
  
      - name: Build with Jekyll
        run: bundle exec jekyll build
